---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-api-secret
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgC5pfNazb0XEkD4x/IZvbHl+ITpqm/hTPLxMKn6ExU9RmvSusN9UrAAGxqLhTcABG0cm3xlgQsro5D3N5Mlntq0Ozm3sQtTds95DvsxEGUPgo6CTOaBDX8hhVhreixIZ9FpR0mMcIOJIfox7jo0iQPb7HAmXGcuscQYq+gWzLQkugThGolHLaTPPGxUsgReLu5n3iJeihOWXpJzHLNLYdAA1tMKA6uHlpQAl/bNmO/ZouPNNYYmiSECeKUIK7a5ar8st7c8b6GRI9rC/KIBctlBYQSyhapw5LOCygkkUnHE9MTcuHOo4un1Xf60knJG+7axSqK/rW3I60xWVqOC7K/2BiDOMe4Z5eU2ce3VriA7lHgMBOjRAs8OE54TuJpYSamIVt3XBmpYRzMxC4l1F99xZzIg50EAThvEXRPAO/YNXC9AYYc7MDm7NeocfmHKDsNBeOZ455TowZv2fX5RJU3BVJLslROX79c3V88NiTFPF0n6/AAWPY6QHSOf8S1Tpnc6MRLBaTkdEh7FygxIvM+FcbdSH4s9JiAjPveZYpfzC16yRMilpZM1jOR2VitiJSdqY906QAec3i/fU8gmMfwDZTfyNZQZleIn15/DVLwyqC7tsRkbcjH1tKiM6KkX3O0FR5dUb72rqg0jVAMp//px1G+tnPU5VaggmtcQ1WSfVHuoy5FixplE4Ze4oAx+TVJ7KPc2JElCQvXaR/R+F/DjOIXyQwMW
    STRIPE_API_KEY: AgCemMLZkV1+VR2vl1cgnFfd20CWLTMyuYItzICTB45e3FDWrrWXIz5nonG+5H9kQ82bcoFpTVezkNfuSrP4aQm+Ehn2qesRU//SNdU8LiBPgX7wOx3Cweq9VtgbCeKHGZ1Gk+j+lR9wxgJcWPuxNecu4+RqnU0gU2+P+WJ6z4kn0kjpDWSs7BRM0QovjxRsyB9asghgQprbx0CsJJOl1EfMnnGz1LdlSWktxlLGpeTU91k/N6hswlQMhl+aU53Peu0CE0a4lJeE82ItJpfIcH+9IC/xsZ+O4POIIXzV6LqgKcSMslchDk802WnaO486nNNdPO/Nlu92MjYj4FLCsQlk0a/mg1/uV2h4+4ZpjFXbn4/hJOwFM4HCULj0mKFkZ0MWnpVTvu588SfoFVQtJFtgDFsDM5r+h7t5/bRl76+iXmr21IvLrtUvYPRKnwUpnuYQKARyeYcBD+A7S3mYmd306mr4nldoeew0QN5Ilxq1RJWj0/IrllHGsu6PmTNzhS8Q1DftM1KXmiMadMpnFAYCmN4lig551nH4TvTe1iyQbPCp4fCDYQZozk9DScSCyMedmZtPokhRRd8tFaK85P84HCJMjuJx9fYqtCt89SA4zcwzx7fOKYQb35zzeSxKv3tZxwIzFYR8ksBRhXonhXeSS/op9cFSIHyAoraaPFTvTqF05rgajpLT3QqqHmpwtZmitm63DOZlZ1wxTGujmsAXrg==
  template:
    metadata:
      name: ledger-api-secret
      namespace: payments
    type: Opaque
