---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-api-secret
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgCmU1+nqfCQfDY9FBg9cjzmy+f9oxlhO7C7qjjExy6jDlELwEx18k8+ZGwBK9jyk6qkXVI19xVSddSXQd/ioKxE1naHCUYiNimFf0GUrqOXKeWSd83gomKnEWzsxU7vb2ABR+iPoY7DhbomevCmzYpSDuGwvoSc+ilEV6vutAkpyBRTLG12lK1mHYykWZK1GW1MZ7mc5TOW3jZqdWkccCXQPbrwH/oNLrd2QQrbpLe9pLfY1A///d08sz7JNqYUgxhepmogC4fs80waP8YLhGa9hxWd5w7D2UhTElZGfP3i3ChmRNnqsWojO3goooA78DLyZcIF3z8N9RAmlq+UxY+0BYfTL5c2YKSRkUKWL4feVBP0dSaHDw3/b3qwqEORkKoRkdXYdHfgfEYfRUkLNprrjAjY2sh5N2KhZeuXHOS8Bim4KTsg/5r7bUIpxxvbazw16I6DFEZYZxURu4R7jC74oraFuKCVgVaZ0YMkzD/dtenP+4dDL8suxJHLdyPm9CDQ4w/MTkZQfsWbGRDj1lNx6eZ4keVImGgIxZvGJYXDHInoPrUL3sar3O2UGqmKjJOjvCtPF2P6jVxqmF1Ma2FFZB/dDfUD7UokdLIvQVAK09k5JqRj+AH74Foj2o1+gEAm1o4/dFGY9IbBo5orJQ/4BpAdrDfxZzJgFbK8xxUOHvqZ1WWu4S+Gv1G28ynFoPok5T4ShE3VYHakcPNQh3GV9wPzleiQ
    STRIPE_API_KEY: AgA9KBzIDl6XxOnUQdkMVZUj6qzDWjO0wGecTgAfQgv4X2YvdXIxk0tK9hpRBRUovtXAC+kkWL5tMGFv6ClR/HGipjWtoFy/xSaOopbzWJbPk4K+CUWoH6S+g4Lt+WWJY6Z65zCeS4f5XAHs/LI9JxYd98FzEi1XyXkcRLs6cXt5BB7ssjT8bYW9+OfRUk001LcHtsFRxWjOLJyhoGTM4AOR7cX9FoHy/l3Lpk4zk1kcBw9Z44/QMh9VgRO0DHvhezbgGu4V28+/V0OK4ctcMCeyi1ilX5Kokq7pUONoW+HXJm91imYjJmDXIvxpTXsYrj3KQh5g4bzjepLd4u1I0XhJB8j6E2piFYpSkdNZE9LO304mQs7PAX4NlkcZ/Z8pWjWrd0kbwcZK6yX4+FpcFqXWuRjhb1JQIgX3a0dIyS3Moyqo7zlbVvRYLW3Dh91in56rTkpioYPfwuHKdf087JhR17QYVI+94Qv8wPdA+PfyJcD9LW3+PXrD2P+dYU6AMKTRbUGIgdauvFqMLhGJk64Bjxou4izQTzBIQYAuL1vvQ6+oy+2FfRdcez/HXD76tIpnkYihvWzuJXorj4XjAPcfuE8a+rPoX6GSeioPYWxjpANpVGEOA/aKSAmynQxBJ/FMGh8QpUwgepxFcBocya/AxVTrKa77uSuGT5Nss00UjFi0bX0ThXntYNMoJjLZkJyfCzwK2iIR8ZnKuPXQzCRmqA==
  template:
    metadata:
      name: ledger-api-secret
      namespace: payments
    type: Opaque
